// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'PagesBaseCard': typeof import("../components/pages/BaseCard.vue")['default'],
    'DashboardBlog': typeof import("../components/dashboard/blog/Blog.vue")['default'],
    'DashboardContactsMyContacts': typeof import("../components/dashboard/contacts/MyContacts.vue")['default'],
    'DashboardProfileCard': typeof import("../components/dashboard/profile/ProfileCard.vue")['default'],
    'DashboardSalesOverviewGchart': typeof import("../components/dashboard/salesOverview/Gchart.js")['default'],
    'DashboardSalesOverview': typeof import("../components/dashboard/salesOverview/SalesOverview.vue")['default'],
    'DashboardTimeline': typeof import("../components/dashboard/timeline/Timeline.vue")['default'],
    'LayoutComponentsHeader': typeof import("../components/layoutComponents/header/Header.vue")['default'],
    'LayoutComponentsSidebar': typeof import("../components/layoutComponents/sidebar/Sidebar.vue")['default'],
    'LayoutComponentsSidebarItems': typeof import("../components/layoutComponents/sidebar/sidebarItems.ts")['default'],
    'PagesButtonsBlock': typeof import("../components/pages/buttons/ButtonsBlock.vue")['default'],
    'PagesButtonsDefault': typeof import("../components/pages/buttons/ButtonsDefault.vue")['default'],
    'PagesButtonsIcon': typeof import("../components/pages/buttons/ButtonsIcon.vue")['default'],
    'PagesButtonsOutlined': typeof import("../components/pages/buttons/ButtonsOutlined.vue")['default'],
    'PagesButtonsRounded': typeof import("../components/pages/buttons/ButtonsRounded.vue")['default'],
    'PagesButtonsSizing': typeof import("../components/pages/buttons/ButtonsSizing.vue")['default'],
    'PagesCardsContentWrap': typeof import("../components/pages/cards/CardsContentWrap.vue")['default'],
    'PagesCardsMedia': typeof import("../components/pages/cards/CardsMedia.vue")['default'],
    'PagesCardsProps': typeof import("../components/pages/cards/CardsProps.vue")['default'],
    'PagesCardsSlots': typeof import("../components/pages/cards/CardsSlots.vue")['default'],
    'PagesCardsTwitter': typeof import("../components/pages/cards/CardsTwitter.vue")['default'],
    'PagesCardsWeather': typeof import("../components/pages/cards/CardsWeather.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyPagesBaseCard': typeof import("../components/pages/BaseCard.vue")['default'],
    'LazyDashboardBlog': typeof import("../components/dashboard/blog/Blog.vue")['default'],
    'LazyDashboardContactsMyContacts': typeof import("../components/dashboard/contacts/MyContacts.vue")['default'],
    'LazyDashboardProfileCard': typeof import("../components/dashboard/profile/ProfileCard.vue")['default'],
    'LazyDashboardSalesOverviewGchart': typeof import("../components/dashboard/salesOverview/Gchart.js")['default'],
    'LazyDashboardSalesOverview': typeof import("../components/dashboard/salesOverview/SalesOverview.vue")['default'],
    'LazyDashboardTimeline': typeof import("../components/dashboard/timeline/Timeline.vue")['default'],
    'LazyLayoutComponentsHeader': typeof import("../components/layoutComponents/header/Header.vue")['default'],
    'LazyLayoutComponentsSidebar': typeof import("../components/layoutComponents/sidebar/Sidebar.vue")['default'],
    'LazyLayoutComponentsSidebarItems': typeof import("../components/layoutComponents/sidebar/sidebarItems.ts")['default'],
    'LazyPagesButtonsBlock': typeof import("../components/pages/buttons/ButtonsBlock.vue")['default'],
    'LazyPagesButtonsDefault': typeof import("../components/pages/buttons/ButtonsDefault.vue")['default'],
    'LazyPagesButtonsIcon': typeof import("../components/pages/buttons/ButtonsIcon.vue")['default'],
    'LazyPagesButtonsOutlined': typeof import("../components/pages/buttons/ButtonsOutlined.vue")['default'],
    'LazyPagesButtonsRounded': typeof import("../components/pages/buttons/ButtonsRounded.vue")['default'],
    'LazyPagesButtonsSizing': typeof import("../components/pages/buttons/ButtonsSizing.vue")['default'],
    'LazyPagesCardsContentWrap': typeof import("../components/pages/cards/CardsContentWrap.vue")['default'],
    'LazyPagesCardsMedia': typeof import("../components/pages/cards/CardsMedia.vue")['default'],
    'LazyPagesCardsProps': typeof import("../components/pages/cards/CardsProps.vue")['default'],
    'LazyPagesCardsSlots': typeof import("../components/pages/cards/CardsSlots.vue")['default'],
    'LazyPagesCardsTwitter': typeof import("../components/pages/cards/CardsTwitter.vue")['default'],
    'LazyPagesCardsWeather': typeof import("../components/pages/cards/CardsWeather.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const PagesBaseCard: typeof import("../components/pages/BaseCard.vue")['default']
export const DashboardBlog: typeof import("../components/dashboard/blog/Blog.vue")['default']
export const DashboardContactsMyContacts: typeof import("../components/dashboard/contacts/MyContacts.vue")['default']
export const DashboardProfileCard: typeof import("../components/dashboard/profile/ProfileCard.vue")['default']
export const DashboardSalesOverviewGchart: typeof import("../components/dashboard/salesOverview/Gchart.js")['default']
export const DashboardSalesOverview: typeof import("../components/dashboard/salesOverview/SalesOverview.vue")['default']
export const DashboardTimeline: typeof import("../components/dashboard/timeline/Timeline.vue")['default']
export const LayoutComponentsHeader: typeof import("../components/layoutComponents/header/Header.vue")['default']
export const LayoutComponentsSidebar: typeof import("../components/layoutComponents/sidebar/Sidebar.vue")['default']
export const LayoutComponentsSidebarItems: typeof import("../components/layoutComponents/sidebar/sidebarItems.ts")['default']
export const PagesButtonsBlock: typeof import("../components/pages/buttons/ButtonsBlock.vue")['default']
export const PagesButtonsDefault: typeof import("../components/pages/buttons/ButtonsDefault.vue")['default']
export const PagesButtonsIcon: typeof import("../components/pages/buttons/ButtonsIcon.vue")['default']
export const PagesButtonsOutlined: typeof import("../components/pages/buttons/ButtonsOutlined.vue")['default']
export const PagesButtonsRounded: typeof import("../components/pages/buttons/ButtonsRounded.vue")['default']
export const PagesButtonsSizing: typeof import("../components/pages/buttons/ButtonsSizing.vue")['default']
export const PagesCardsContentWrap: typeof import("../components/pages/cards/CardsContentWrap.vue")['default']
export const PagesCardsMedia: typeof import("../components/pages/cards/CardsMedia.vue")['default']
export const PagesCardsProps: typeof import("../components/pages/cards/CardsProps.vue")['default']
export const PagesCardsSlots: typeof import("../components/pages/cards/CardsSlots.vue")['default']
export const PagesCardsTwitter: typeof import("../components/pages/cards/CardsTwitter.vue")['default']
export const PagesCardsWeather: typeof import("../components/pages/cards/CardsWeather.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyPagesBaseCard: typeof import("../components/pages/BaseCard.vue")['default']
export const LazyDashboardBlog: typeof import("../components/dashboard/blog/Blog.vue")['default']
export const LazyDashboardContactsMyContacts: typeof import("../components/dashboard/contacts/MyContacts.vue")['default']
export const LazyDashboardProfileCard: typeof import("../components/dashboard/profile/ProfileCard.vue")['default']
export const LazyDashboardSalesOverviewGchart: typeof import("../components/dashboard/salesOverview/Gchart.js")['default']
export const LazyDashboardSalesOverview: typeof import("../components/dashboard/salesOverview/SalesOverview.vue")['default']
export const LazyDashboardTimeline: typeof import("../components/dashboard/timeline/Timeline.vue")['default']
export const LazyLayoutComponentsHeader: typeof import("../components/layoutComponents/header/Header.vue")['default']
export const LazyLayoutComponentsSidebar: typeof import("../components/layoutComponents/sidebar/Sidebar.vue")['default']
export const LazyLayoutComponentsSidebarItems: typeof import("../components/layoutComponents/sidebar/sidebarItems.ts")['default']
export const LazyPagesButtonsBlock: typeof import("../components/pages/buttons/ButtonsBlock.vue")['default']
export const LazyPagesButtonsDefault: typeof import("../components/pages/buttons/ButtonsDefault.vue")['default']
export const LazyPagesButtonsIcon: typeof import("../components/pages/buttons/ButtonsIcon.vue")['default']
export const LazyPagesButtonsOutlined: typeof import("../components/pages/buttons/ButtonsOutlined.vue")['default']
export const LazyPagesButtonsRounded: typeof import("../components/pages/buttons/ButtonsRounded.vue")['default']
export const LazyPagesButtonsSizing: typeof import("../components/pages/buttons/ButtonsSizing.vue")['default']
export const LazyPagesCardsContentWrap: typeof import("../components/pages/cards/CardsContentWrap.vue")['default']
export const LazyPagesCardsMedia: typeof import("../components/pages/cards/CardsMedia.vue")['default']
export const LazyPagesCardsProps: typeof import("../components/pages/cards/CardsProps.vue")['default']
export const LazyPagesCardsSlots: typeof import("../components/pages/cards/CardsSlots.vue")['default']
export const LazyPagesCardsTwitter: typeof import("../components/pages/cards/CardsTwitter.vue")['default']
export const LazyPagesCardsWeather: typeof import("../components/pages/cards/CardsWeather.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
